export const apiConfig = {
  BASE_URL: 'https://aqa-course-project.app',
  ENDPOINTS: {
    CUSTOMERS: '/api/customers',
    CUSTOMERS_ALL: '/api/customers/all',
    CUSTOMER_BY_ID: (id: string) => `/api/customers/${id}/`,
    LOGIN: '/api/login',
    METRICS: '/api/metrics',
    PRODUCTS: '/api/products',
    PRODUCT_BY_ID: (id: string) => `/api/products/${id}/`,
    PRODUCTS_ALL: '/api/products/all',
    ORDERS: '/api/orders',
    ORDERS_BY_ID: (id: string) => `/api/orders/${id}/`,
    ASSIGN_MANAGER: (orderId: string, managerId: string) =>
      `/api/orders/${orderId}/assign-manager/${managerId}`,
    UNASSIGN_MANAGER: (orderId: string) => `/api/orders/${orderId}/unassign-manager`,
    ORDER_COMMENTS_ADD: (id: string) => `/api/orders/${id}/comments`,
    ORDER_COMMENTS_DELETE: (id: string, commentId: string) => `/api/orders/${id}/comments/${commentId}`,
    ORDER_RECEIVE: (id: string) => `/api/orders/${id}/receive`,
    ORDER_DELIVERY: (id: string) => `/api/orders/${id}/delivery`,
    ORDER_STATUS: (id: string) => `/api/orders/${id}/status`,
    NOTIFICATIONS: '/api/notifications',
    NOTIFICATIONS_BY_ID_READ: (id: string) => `/api/notifications/${id}/read`,
    NOTIFICATIONS_ALL_READ: '/api/notifications/mark-all-read',
    CUSTOMER_ORDERS: (customerId: string) => `/api/customers/${customerId}/orders`,
  },
} as const;
