#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-commit checks..."

# Run linting checks
echo "📝 Checking code style..."
npm run lint:fix

# Run formatting checks
echo "🎨 Checking code formatting..."
npm run format:fix
git add .

echo "✅ Pre-commit checks passed!" 